language: ruby
rvm:
  - 2.5.3
services:
  - postgresql
env:
  - RAILS_ENV=test
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  # - bundle exec rubocop
  - bundle exec rspec spec/controllers
  - bundle exec rspec spec/features
  - bundle exec rspec spec/helpers
  - bundle exec rspec spec/models
  # - bundle exec rspec spec/requests
  - bundle exec rspec spec/routing
  # - bundle exec rspec spec/views
